### Get all contacts
GET https://cse-341-project1-1k5k.onrender.com/Contacts HTTP/1.1

### Get single contact by ID
GET https://cse-341-project1-1k5k.onrender.com/Contacts/682ee73e8c63ce09a55c71f6 HTTP/1.1
